name: react-native-android-build-apk

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'packages/app-desktop/**'
      - 'packages/app-cli/**'
      - 'packages/server/**'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /usr/share/swift || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          sudo rm -rf /usr/local/share/boost || true
          sudo rm -rf /usr/local/share/powershell || true
          docker system prune -af || true
          df -h /

      - name: Install Linux dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get install -y libsecret-1-dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack and Install Dependencies
        run: |
          corepack enable
          yarn install
        env:
          SKIP_ONENOTE_CONVERTER_BUILD: 1

      - name: Build Monorepo Packages
        run: |
          yarn run build

      - name: Build Android App
        run: |
          cd packages/app-mobile/android
          # 自动注入 debug 签名以允许 release 打包
          sed -i -- 's/signingConfig signingConfigs.release/signingConfig signingConfigs.debug/' app/build.gradle
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Verify alignment
        run: |
          cd packages/app-mobile/android/app
          APK_FILE="./build/outputs/apk/release/app-release.apk"
          if [ ! -f "$APK_FILE" ]; then
            echo "APK file not found."
            exit 1
          fi
          echo "APK generated successfully at $APK_FILE"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: joplin-android-apk
          path: packages/app-mobile/android/app/build/outputs/apk/release/*.apk
          retention-days: 7
